### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by firstnecron** [firstnecron/tt-library-manager#1]
**Models**
- [ ] Project includes the following Sequelize models: books, patrons, loans

**Home Screen**
Includes links to all of the following pages, and links lead to the correct page:
- [ ] Books: New Book, List All, List Overdue, List Checked Out
- [ ] Patrons: New Patron, List All
- [ ] Loans: New Loan, List All, Overdue, List Checked Out

**Navigation**
- [ ] Includes a main navigation menu that appears on every page.
- [ ] Main navigation contains working links to: Books (all book listings page), Patrons (all patron listing page), Loans (all loans listing page)

**Books Listing Page**
- [ ] Displays table of books with the following columns: Book Title, Author, Genre, Year Released (First Published)
- [ ] Each book title links to the book's detail page.
- [ ] Includes option to filter books by “All”, “Overdue”, and “Checked Out”
- [ ] Includes a button to create a new book
- [ ] (Extra) Has working pagination for books list.
- [ ] (Extra) Has working search functionality. Can search by title, author, genre, etc.

**New Book Page**
- [ ] Includes a form to add a new book. Form contains the following fields: Title (required), Author (required), Genre (required), First Published (optional)
- [ ] An error is displayed if the form is submitted with blank or invalid data in required fields. For example: “This field is required.”
- [ ] When the form is submitted successfully, user is redirected to the Books Listing Page and the new book appears in the list.

**Book Detail Page**
- [ ] Contains a Loan History table with the following columns: book name, patron, loaned on, return by, returned on and action.
- [ ] If the book is checked out, the “Action” column contains a link to return the book
- [ ] Includes a form allowing the user to update the book, with the following input fields: Title (required), Author (required), Genre (required), First Published (optional)
- [ ] When the form is submitted successfully, user is redirected to the Books Listing Page and the book appears in the list with updated information.

**Loans Listing Page**
- [ ] Contains option to filter books by “All”, “Overdue”, and “Checked Out”
- [ ] Includes a button that links to the New Loan Page
- [ ] Contains a table of loans with the following columns: Book Title, Patron, Loaned On, Return By, Returned On, Action
- [ ] The “patron” field links to the patron who checked out the book
- [ ] If the book is checked out, the “Action” column contains a link to return the book
- [ ] (Extra) Has working pagination

**New Loan Page**
- [ ] Includes the following form fields: Book (required), Patron (required), Loaned On (required), Returned By (optional)
- [ ] Patron and Book are select dropdown menus with the complete list of patrons and books.
- [ ] “Loaned on” is pre-populated with today’s date, in YYYY-MM-DD format. “Return by” is 7 days in the future.
- [ ] An error is displayed if the form is submitted with blank or invalid data in required fields. For example: “This field is required.”
- [ ] When the form is submitted successfully, a loan is created in a the database

**Return Book Page**
- [ ] Displays book title, the patron who borrowed the book, the loaned on and return by dates.
- [ ] Has the “Returned on” field pre-populated with today’s date.
- [ ] Includes a button to return the book
- [ ] An error is displayed if the form is submitted with blank or invalid data in required fields. For example: “This field is required.”
- [ ] When the form is submitted successfully, the loan should be updated in the database and the page should redirect to the loans listing page.

**Patrons Listing Page**
- [ ] Displays a table listing patron’s information: Name, Address, Email, Library ID, Zip Code
- [ ] Each patron’s name links to the corresponding patron detail page
- [ ] (Extra) Has working pagination.
- [ ] (Extra) Has working search facility. Can search by first_name, last_name,library_id, etc.

**Patron Detail Page**
- [ ] Contains a form with the following fields (all fields should be required fields): First Name, Last Name, Address, Email, Library ID, Zip Code
- [ ] An error is displayed if the form is submitted with blank or invalid data in required fields. For example: “This field is required.”
- [ ] When the form is submitted successfully, the patron should be updated in the database and the page should redirect to the patron page.
- [ ] Shows a Loan History table
- [ ] Each entry in the loans table should have links to books, patrons and if the book is checked out, the link to the return book page.

**New Patron Page**
- [ ] Has labels that correctly select form inputs. All fields should be required, and should include: First Name, Last Name, Address, Email, Library ID, Zip Code
- [ ] An error is displayed if the form is submitted with blank or invalid data in required fields. For example: “This field is required.”
- [ ] When the form is submitted successfully, a patron should be created in the database and the page should redirect to the patrons listing page.
